#!/usr/bin/python
#
# io il python lo odio...
#

from    vismach import *
import  hal
import  math
import  sys

# give endpoint Z values and radii
# resulting cylinder is on the Z axis
class HalToolCylinder(CylinderZ):
    def __init__(self, comp, *args):
	CylinderZ.__init__(self, *args)
	self.comp = comp

    def coords(self):
        return -self.comp.tool_length, 20, 0, 20

c = hal.component("dydegui")
c.newpin("joint0", hal.HAL_FLOAT, hal.HAL_IN)
c.newpin("joint1", hal.HAL_FLOAT, hal.HAL_IN)
c.newpin("joint2", hal.HAL_FLOAT, hal.HAL_IN)
c.newpin("joint3", hal.HAL_FLOAT, hal.HAL_IN)
c.newpin("joint4", hal.HAL_FLOAT, hal.HAL_IN)
c.newpin("joint5", hal.HAL_FLOAT, hal.HAL_IN)
c.newpin("tool_length", hal.HAL_FLOAT, hal.HAL_IN)
c.ready()

pivot_len=100
tool_radius=25

for setting in sys.argv[1:]: exec setting

tooltip = Capture()

# tool
tool = Collection(  [HalTranslate([tooltip], c, "tool_length", 0,0,-1),
                    HalToolCylinder(c),
                    ])
tool = Translate(   [tool], 0, 0, -pivot_len-150)
tool = Collection(  [tool])
tool = HalRotate(   [tool],c,"joint2",1,0,-1,0)


# wrist
wrist = Collection( [tool,
                    Box(-100,-100,100, 100,100,150),
                    ])
wrist = HalTranslate([wrist],c,"joint5",0,1,0)

# ram
ram = Collection(   [wrist,
                    # asse Y
                    Box(0,0,0, 900,100,100) ])
ram = Translate(    [ram], 500, 0, 200)

# trasportato da X
ram = HalTranslate( [ram],c,"joint0",0,1,0)

ram = Collection(   [ram,
                    # asse U
                    Box(0,0,0, 900,100,100) ])
ram = Translate(    [ram], 1000,0,200)

# trasportato da V
ram = HalTranslate( [ram],c,"joint4",1,0,0)

ram = Collection(   [ram,
                    # X
                    Box(0,0,0, 100,2000,200),
                    ])

                    # CylinderZ(pivot_len, 100, 0.0, 50),
                    # Box(-100,-100,pivot_len, 100,100,pivot_len+50),


ram = HalTranslate( [ram],c,"joint3",0,1,0)

#
work = Capture()

# tavola 
table = Collection( [work])

# model
model = Collection( [ram, table])

main(model, tooltip, work, 1500)

